### ISSUE TITLE
Configuration file support

### ISSUE THREAD

**Issue by crazyscot** [crazyscot/qcp#17]
Like ssh and other utilities, I'd like to be able to set defaults so I don't have to type `--rx whatever` every time.

Ideas:

* Local config file that provides default settings
* Settings overridable 
* User and system-wide config files
* The two endpoints negotiate bandwidth based on their configuration
* Useful error reporting (e.g. syntax error at line 42 of <filename>) is important
* User-friendly file format (while TOML is handy, I don't consider it friendly enough; I am thinking about INI files or something close).

**Comment by Lightjohn** [comment]
Among the configuration files would it be an option to use ssh config files to get server name equivalent IP and user name?

**Comment by crazyscot** [comment]
@Lightjohn I like the idea! It's a separate feature, so I have attempted to capture it as #22; does that describe what you had in mind?
