### ISSUE TITLE
Get host name/IP from ssh config files

### ISSUE THREAD

**Issue by crazyscot** [crazyscot/qcp#22]
If a user has set up a host name alias in `.ssh/config` or `/etc/ssh/config`:

```
...
Host some-server
    Hostname some-server.somewhere.fqdn
    User foo
    ...
```

then it is reasonable to suppose they would want qcp to use that hostname alias as well.

Or, in other words: If I can `ssh some-server` then I ought to be able to `qcp` directly to that server as well, applying the same aliasing rules. To this end, it might also be reasonable to support `CanonicalDomains`, `CanonicalizeHostname` and friends.

**Comment by Lightjohn** [comment]
From what I have done personally I think we could expect to read at least 3 information:
```
Host MyServer
   Hostname AnIpOrALongURL
   User lightjohn
   Port 2222
```
**Hostname**, **User** and **Port**
which would indeed make qcp very close to scp which make it easy to test.

**Comment by crazyscot** [comment]
> **Hostname**, **User** and **Port** which would indeed make qcp very close to scp which make it easy to test.

Have I missed something? I'm not quite following what qcp would do with the user and port.

qcp spawns an ssh process to establish the control channel. As in, it runs `ssh hostname qcp --server` (or `ssh user@host...` if you used that syntax). So the ssh binary will read its own config and use the configured remote username and ssh port, if any. The qcp session protocol doesn't need to know either of those.

**Comment by Lightjohn** [comment]
Oh I see, I was the one missing the details :) 

My issue at first is that I can't use name defined in my ssh config and so I had to add the ip so I concluded that you were not using ssh internally.

So if you spawn an ssh process why would the server name not be recognized? 

Sorry for jumping to conclusions

**Comment by crazyscot** [comment]
> So if you spawn an ssh process why would the server name not be recognized?
> 
> Sorry for jumping to conclusions

No worries :upside_down_face: 

qcp does need to know about server names when setting up the session channel. At the moment all it does is take the server name you provided on the command line and perform a DNS lookup, without looking at whatever aliasing you've set up in your ssh config.
